#ifndef LIB_H
#define LIB_H

#define DEBUG

#ifdef DEBUG

#define ON_DEBUG(...) __VA_ARGS__

#else

#define ON_DEBUG(...)

#endif


//  Colors for terminal
const char* const MY_RED = "\033[31m";
const char* const MY_YELLOW = "\033[33m";
const char* const MY_GREEN = "\033[32m";
const char* const MY_RESET = "\033[0m";

//  Sizes of static arrays
/// @brief Len less than 8 will have warning from stack protector
const int MAX_STATEMENT_LEN = 9; // >= 8 to avoid warning
const int MAX_STATEMENTS = 10;

const int MAX_FORMAT_LINE_LEN = 50;
const int MAX_NUMBER_LEN = 20;
const int MAX_FILENAME_LEN = 20;

//  Trash char
const char TRASH_CHAR = 'a';

//  Statuses
/// @brief Mode, which User chose or error
enum INPUT_MODE_STATUS {
    SOLVING = 0,
    TESTING = 1,
    FUNCTION_GRAPHIC = 2,
    USER_INPUT_MODE_ERROR = 3
};

/// @brief Testing mode, which User chose or error
enum TESTING_MODE_STATUSES {
    MANUAL_TESTING = 0,
    FILE_TESTING = 1, // input from file
    UNIT_TESTING = 2, // testing on set of cases
    TESTING_MODE_INPUT_ERROR = 3
};

/// @brief Statuses of checking generated solution in Solving mode
enum CHECK_STATUSES {
    CHECK_SUCCESS = 1,
    CHECK_FAIL = 0,
    CHECK_ERROR = -1
};

/// @brief First, second and third are coefs, which are entered by User. Bad numbers are nan, inf.
enum INPUT_STATUSES {
    INPUT_ERROR_FIRST = 0,
    INPUT_ERROR_SECOND = 1,
    INPUT_ERROR_THIRD = 2,

    INPUT_ERROR_AFTER_THIRD = 3,
    INPUT_ERROR_BAD_NUMBERS = 4,
    UNKNOWN_INPUT_ERROR = 5,
    INPUT_CORRECT = 6
};

enum RUN_SINGLE_TEST_STATUSES {
    TEST_CHECK_SUCCESS = 0,
    TEST_CHECK_FAIL = 1,
    TEST_CHECK_ERROR = 2
};

enum RUN_ALL_TESTS_STATUSES {
    RUN_ALL_TESTS_SUCCESS = 0,
    RUN_ALL_TESTS_ERROR = 1
};

/// @brief Statements are phrases expected to be entered by User
struct statementInfo {
    const char* const statements[MAX_STATEMENTS];
};

const struct statementInfo YES_NO = {{"yes", "no"}};

const statementInfo SOLVE_TEST_GRAPHICAL = {{"solve", "test", "graph"}};

const statementInfo MANUAL_FILE_AUTO = {{"manual", "file", "unit"}};

/// @brief Structs to store info about tests
struct equationCoefsTest {
    equationCoefs coefs; //defined in QuadraticSolver.h

    QUADRATIC_SOLVER_STATUSES refCntRoots;
    double refRoot1, refRoot2;
};

//  Functions to work with structs

struct equationCoefs equationCoefsInit(void);

void printEquationCoefsTest(equationCoefsTest test);

/// @brief Initialize structure by pointer on it
/// @param ptrCoefs Pointer to structure
void equationCoefsInitPointers(equationCoefs* ptrCoefs);

//  UI main menu functions

/// @brief Greets User by printing text
void greetings(void);

INPUT_MODE_STATUS userChoosingMode(void);

void chooseMode(INPUT_MODE_STATUS inputModeStatus);

TESTING_MODE_STATUSES userChoosingTestingMode(void);

//  Functions to handle User text input

/// @brief Creating format line for fscanf to read first scanfLen symbols
void getFormatLine(char* formatLine, size_t scanfLen);

/// @brief To read statementLine, expecting to get string similar in statementInfo  
void getStatementLine(char *statementLine, statementInfo info);

/// @brief Transforms checkStatus to string with explanation, suitable for output to User
const char* const getStringCheckStatus(CHECK_STATUSES checkStatus);


// Functions to process User input lines

/// @brief Skips all ' ' and '\t' chars and if current char is '\n' or EOF, then stop, otherwise read to such symbol
bool processEnd(void);

/// @brief Skips all ' ' and '\t' chars and if current char is '\n' or EOF, then returns true, otherwise - false  
bool goodEnd(void);

/// @brief Reads all chars until '\n' or EOF 
void readToEnd(void);



//  Functions to handle User attempts input

/// @brief Prints invitation to enter positive numbers
void greetingsIntInput(void);

/// @brief Tries to read the the positive integer, otherwise asking again (there is no other stop condition)
int getPositiveIntInputSafe(void);

//  Functions, used in real time solving case
// 1.Interaction&Solve

/// @brief Wrapper function for handling Solving case
/// @param Number of equations to solve
void solveRealTime(int attempts);

/// @brief Function, which asks User to continue solving equations or not? 
bool resume(void);

void printAttempts(int attempts);

//  2.Check roots & print them

/// @brief Function, which is checking generated by program roots (in Solving case)
CHECK_STATUSES checkRoots(const equationCoefs coefs,
 QUADRATIC_SOLVER_STATUSES cntRoot, const double eqRoot1, const double eqRoot2);

/// @brief a*x*x + b*x + c == 0?
int checkSingleRoot(const equationCoefs coefs, const double x);

/// @param cntRoots 8 if there is infinite number of roots
/// @param eqRoot1 NAN if there is no root
/// @param eqRoot2 NAN if there is no root
void printRoots(QUADRATIC_SOLVER_STATUSES cntRoots, const double eqRoot1, const double eqRoot2);

// Real time solving case ended

 
// Functions, handling coefficients input

/// @brief Tranforms input status to string suitable for User
const char* const getStringInputStatus(INPUT_STATUSES inputStatus);

/// @brief  Gets coeficients of equation from file or stdin
INPUT_STATUSES getCoefInput(equationCoefs* ptrCoefs, FILE* ptrFile);

// Functions for testing

/// @brief  Transforms status of running all tests to string suitable for User
const char* const getStringRunAllTestsStatus(RUN_ALL_TESTS_STATUSES runAllTestsStatus);

RUN_ALL_TESTS_STATUSES runAllTests(TESTING_MODE_STATUSES testingModeStatus);

/// @brief Transforms status of running single test to string suitable for User 
const char* const getStringTestCheckStatus(RUN_SINGLE_TEST_STATUSES runSingleTestStatus);

RUN_SINGLE_TEST_STATUSES runSingleTest(equationCoefsTest test);

//  Function for manual & file testing

/// @brief  Function wraper for handling all testing modes (manual, file, unit)
RUN_ALL_TESTS_STATUSES userTesting(const char* const mode);

//  Function for unit testing
RUN_ALL_TESTS_STATUSES unitTesting(void);

// Function, covering case graphic function

/// @brief Function, handling graphical mode
void buildFunctionGraphic(void);
// End of case graphic function



// Working with files&stdin functions

/// @brief This function prints greetings, user expected to enter filename, function tries to open file with param mode access mode
/// @param String to print to User
/// @param Mode to open file with
/// @return If file cannot be opened, then NULL returns, otherwise FILE pointer returns 
FILE* acessFile(const char* const greetings, const char* const mode);

/// @brief This function handles exceptions while reading equation coefficients from User input
/// @param A pointer to struct, storaging coefficients of equation 
/// @param A pointer to file OR stdin
INPUT_STATUSES fileCoefInput(equationCoefs* ptrCoefs, FILE* ptrFile); // note: this function is used in real time case!

/// @brief This function handles exceptions while reading reference values,
/// if something is wrong, string with explanation of error is printed
/// @param coefsTest A pointer to struct, stroraging reference values 
/// @param ptrFile A pointer to file OR stdin
INPUT_STATUSES fileRefInput(equationCoefsTest* coefsTest, FILE* ptrFile);

/// @brief This function reads reference values from User input
/// @param coefsTest A pointer to struct, storaging reference values
/// @param ptrFile A pointer to file OR stdin
INPUT_STATUSES getRefInput(equationCoefsTest* ptrTest, FILE* ptrFile);

//  Functions for checking User numeric input

/// @brief Checks are equation coefs finite? 
bool isGoodCoefs(equationCoefs* ptrCoefs);

/// @brief Checks do reference values have valid format? Number of roots should be 0, 1, 2 or 8 (INF), both roots should be finite
bool isGoodRef(equationCoefsTest* ptrTest);

// math functions
size_t max_size_t(size_t op1, size_t op2);


#endif /*LIB_H*/
